import type {Metadata} from "next";

import {NextIntlClientProvider} from "next-intl";
import "./globals.css";
import {getMessages} from "next-intl/server";
import { Link } from "@/navigation";

export const metadata: Metadata = {
  title: "pingmind",
  description: "Generated by appncy",
};

interface Props {
  children: React.ReactNode;
  params: {locale: string};
}

export default async function RootLayout({children, params: {locale}}: Props) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="scheme-light dark:scheme-dark bg-background text-foreground container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4 font-sans antialiased">
        <NextIntlClientProvider messages={messages} timeZone="UTC">
          <header className="text-xl font-bold leading-[4rem]">
            <Link href="/">pingmind</Link>
            <Link className="mx-5" href="/login">login</Link>
          </header>
          {children}
          <footer className="text-center leading-[4rem] opacity-70">pingmind</footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
